// Generated by CoffeeScript 1.9.1
(function() {
  var ADKEY, Extends, LGKEY, OPKEY, TYKEY, additionEx, fns, logicEx, operationEx, typeEx, u;

  typeEx = require('./type');

  additionEx = require('./addition');

  operationEx = require('./operation');

  logicEx = require('./logic');

  u = require('../util');

  OPKEY = 'operation';

  ADKEY = 'addition';

  TYKEY = 'type';

  LGKEY = 'logic';

  module.exports = Extends = {};

  Extends[OPKEY] = operationEx;

  Extends[ADKEY] = additionEx;

  Extends[TYKEY] = typeEx;

  Extends[LGKEY] = logicEx;

  fns = ['has', 'extend', 'get', 'include'];

  fns.forEach(function(key) {
    return Extends[key] = function(type) {
      var args;
      if (!this[type]) {
        return false;
      }
      args = u.slice(arguments, 1);
      return this[type][key].apply(this[type], args);
    };
  });

}).call(this);
