// Generated by CoffeeScript 1.9.1
(function() {
  var Base, DATA, _, u;

  _ = require('lodash');

  u = require('../util');

  Base = require('./extend');

  DATA = {
    $and: function() {
      var args;
      args = u.slice(arguments);
      return _.reduce(args, function(a, b) {
        return a && b;
      });
    },
    $or: function() {
      var args;
      args = u.slice(arguments);
      return _.reduce(args, function(a, b) {
        return a || b;
      });
    },
    $xor: function() {
      var args;
      args = u.slice(arguments);
      return _.reduce(args, function(a, b) {
        return a ^ b;
      });
    }
  };

  module.exports = new Base({
    Data: DATA,
    has: function(str) {
      var i, key, keys, len;
      if (!str) {
        return false;
      }
      str = "" + str;
      keys = Object.keys(this.Data);
      for (i = 0, len = keys.length; i < len; i++) {
        key = keys[i];
        if (str.indexOf(key) === 0) {
          return true;
        }
      }
      return false;
    }
  });

}).call(this);
