// Generated by CoffeeScript 1.9.1
(function() {
  var Base, THIRDS, TYPES, _;

  _ = require('lodash');

  Base = require('./extend');

  TYPES = {};

  THIRDS = [];

  module.exports = new Base({
    Data: TYPES,
    THIRDS: THIRDS,
    check: function(arr, type) {
      var handler;
      handler = this.get(type);
      if (!handler) {
        return false;
      }
      return _.reduce(_.map(arr, handler), function(a, b) {
        return a && b;
      });
    }
  });

}).call(this);
