// Generated by CoffeeScript 1.9.1
(function() {
  var Extends, Rule, RuleSet, _, addition, operation, ref, system, type;

  _ = require('lodash');

  Extends = (ref = require('./extends'), addition = ref.addition, type = ref.type, operation = ref.operation, system = ref.system, ref);

  Rule = require('./rule');

  RuleSet = require('./ruleSet');

  module.exports = {
    Extends: Extends,
    extendOperation: _.bind(operation.extend, operation),
    extendAddition: _.bind(addition.extend, addition),
    extendType: _.bind(type.extend, type),
    includeOperation: _.bind(operation.include, operation),
    includeAddition: _.bind(addition.include, addition),
    includeType: _.bind(type.include, type),
    check: function(rset, obj) {
      if (!(rset instanceof RuleSet)) {
        rset = new RuleSet(rset);
      }
      return rset.check(obj);
    },
    Rule: Rule,
    RuleSet: RuleSet
  };

}).call(this);
